version: '3'
services:
  backend:
    build: ./backend
    ports:
      - 8081:8080
    environment:
      - DB_CONNECTION=jdbc:postgresql://database:5432/postgres
      - DB_USERNAME=user
      - DB_PASSWORD=pass
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      - BACKEND_URL=backend
      - BACKEND_PORT=8080
  database:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    image: postgres
